name: squidpy
channels:
-   conda-forge
-   bioconda
-   r
dependencies:
-   python=3.8
-   openpyxl
-   jupyterlab
-   pandas>=1.5.0
-   scipy
-   anndata
-   scanpy
-   scanorama
-   napari
-   r-essentials
-   pip
-   pip:
    -   squidpy>=1.2.0
    -   ncem
